spring:
  application:
    name: produce-msg-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.118.103:3306/mq_design?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: root
    password: root
    druid:
      # 初始化时建立物理连接的个数
      initial-size: 5
      # 连接池的最小空闲数量
      min-idle: 5
      # 连接池最大连接数量
      max-active: 20
      # 获取连接时最大等待时间，单位毫秒
      max-wait: 60000
      # 申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      test-while-idle: true
      # 既作为检测的间隔时间又作为testWhileIdel执行的依据
      time-between-eviction-runs-millis: 60000
      # 销毁线程时检测当前连接的最后活动时间和当前时间差大于该值时，关闭当前连接(配置连接在池中的最小生存时间)
      min-evictable-idle-time-millis: 30000
      # 用来检测数据库连接是否有效的sql 必须是一个查询语句(oracle中为 select 1 from dual)
      validation-query: select 'x'
      # 申请连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
      test-on-borrow: false
      # 归还连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
      test-on-return: false
      # 是否缓存preparedStatement, 也就是PSCache,PSCache对支持游标的数据库性能提升巨大，比如说oracle,在mysql下建议关闭。
      pool-prepared-statements: false
      # 置监控统计拦截的filters，去掉后监控界面sql无法统计，stat: 监控统计、Slf4j:日志记录、waLL: 防御sqL注入
      filters: stat,wall,slf4j
      # 要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。在Druid中，不会存在Oracle下PSCache占用内存过多的问题，可以把这个数值配置大一些，比如说100
      filter-class-names:
      max-pool-prepared-statement-per-connection-size: -1
      # 合并多个DruidDataSource的监控数据
      use-global-data-source-stat: true
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connect-properties:
        druid.stat.mergeSql: true
        druid.stat.slowSqlMillis: 5000
      #监控平台
      stat-view-servlet:
        allow: 127.0.0.1
        url-pattern: /druid/*
        enabled: true
        reset-enable: false
        login-username: admin
        login-password: admin
  #邮件配置
  mail:
    default-encoding: utf-8
    host: smtp.163.com
    username: wuankang588@163.com
    password: KFZFhzsRhhZitXQW
  #邮件模板
  thymeleaf:
    cache: false
    prefix: classpath:/templates/

  rabbitmq:
    host: 192.168.118.103
    port: 5672
    virtual-host: /
    username: guest
    password: guest
    listener:
      simple:
        acknowledge-mode: auto
    connection-timeout: 3000
    template:
      exchange: orderExchange
      routing-key: create
      default-receive-queue: orderQueue

#自定义延迟处理器配置
msg:
  delay:
    queue:
      delay-msg-delay-queue-capacity: 10000
      delay-send-retry-delay-queue-capacity: 10000

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wak.producemsg.entities
  configuration:
    map-underscore-to-camel-case: true

logging:
  config: classpath:log4j2-spring.xml

thread:
  pool:
    core-pool-size: 5
    max-pool-size: 5
    keep-alive-time: 3
    queue-capacity: 100